### ISSUE TITLE
Doesn't work for private orgs?

### ISSUE THREAD

**Issue by agzam** [ag91/emacs-slack#2]
**Describe the bug**

I'm trying to use it for an org that requires SSO via Okta, and it doesn't seem to work. Auth is tricky, but even after that, the package seems to be unusable, I'm not sure how to debug this better. Simple, password-protected orgs (e.g. clojurians.slack.com) appear to be working fine.

**To Reproduce**
1. Use it for Private Org that requires SSO
2. `(slack-refresh-token)` and set the token and the cookie
3. `(slack-start)` - it may take a while, it goes into `Fetching next cursor...` phase
4. `(slack-select-rooms)`:
```
Debugger entered--Lisp error: (cl-no-applicable-method slack-team-ims nil)
```
5. `(slack-channel-select)` - same error: `(cl-no-applicable-method slack-team-channels nil)`

**Environment:**
 - OS: MacOS Sonoma 14.7.1 
 - Emacs Version: GNU Emacs 30.0.92
 - emacs-slack Version: current 'master'

**Comment by ag91** [comment]
hello @agzam,
random thought: could you try with the new `:enterprise-token`  setting? https://github.com/ag91/emacs-slack/commit/472c48673f21148d85c069e8f404584349e780ca

To debug you can see what the curl calls are returning. It is going to be a bit noisy, but you can set:
`(setq slack-log-level 'debug)` or `'trace` for more and then run `slack-start` (it really will overuse your minibuffer, so a bit of patience until I get some time to send those logs to a file or something.

**Comment by agzam** [comment]
How would `(slack-register-team` block would look like in this case? I can't create one without `:token` key. Do I have to set both `:token` and `:enterprise-token`? Hmm. that worked. I think

**Comment by agzam** [comment]
I noticed another (completely unrelated) issue, we have private channels, and I couldn't find a way to get to use those.

Aside that, I was able to send messages in other (public channels). Thank you. Closing this now.

**Comment by ag91** [comment]
@agzam I became the maintainer of the original repository: so [this fork merged in there](https://github.com/emacs-slack/emacs-slack). Could you open issues on there (also if you use that you will have some fancy new features ;)

**Comment by ag91** [comment]
also @agzam did you try `slack-im-open` to start the conversation and then select it? I am not sure why that is needed, probably needs a fix as well.
