### ISSUE TITLE
Can't seem to work with multiple Orgs

### ISSUE THREAD

**Issue by agzam** [ag91/emacs-slack#3]
**Describe the bug**

I want to use the package with multiple Slack orgs. Currently I have two orgs of interest: one is private/enterprise, another is public - clojurians.slack.com. 

As described in #2 they need different method of authenticating and that's okay.

The problem seems to appear when I try to register both orgs and then try to switch between them.

It would initially start, load the rooms, users, etc. (which takes significant amount of time)

And then I try `slack-change-current-team`, select the other team and I get `Failed to request slack-authorize: invalid_auth`.

**Comment by ag91** [comment]
oh, that is cool: I didn't test that because I usually access only one team at the time.
I will open this on the original repo because I became its maintainer: https://github.com/emacs-slack/emacs-slack

**Comment by ag91** [comment]
https://github.com/emacs-slack/emacs-slack/issues/596
